spring:
  profiles:
      default: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/choi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true

jwt:
  secret: ${JWT_SECRET}