spring:
  profiles:
      default: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/choi
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true

jwt:
  secret: ${JWT_SECRET}
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      accessKey: ${AWS_S3_ACCESSKEY}
      secretKey: ${AWS_S3_SECRETKEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
